--- #YAML:1.0
name:                Test-WWW-Mechanize
version:             1.14
abstract:            Testing-specific WWW::Mechanize subclass
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp::Assert::More:            0
    HTTP::Server::Simple:          0.07
    Test::LongString:              0.07
    Test::More:                    0
    URI::file:                     0
    WWW::Mechanize:                1.24
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Lester <andy@petdance.com>
