--- #YAML:1.0
name:               Test-WWW-Mechanize
version:            1.26
abstract:           Testing-specific WWW::Mechanize subclass
author:
    - Andy Lester <andy@petdance.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Assert::More:   0
    HTTP::Server::Simple:  0.35
    HTTP::Server::Simple::CGI:  0
    perl:                 5.008
    Test::Builder::Tester:  1.09
    Test::LongString:     0.12
    Test::More:           0
    URI::file:            0
    WWW::Mechanize:       1.24
resources:
    bugtracker:   http://code.google.com/p/www-mechanize/issues/list
    homepage:     http://code.google.com/p/www-mechanize/
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/www-mechanize-users
    Repository:   http://code.google.com/p/www-mechanize/source
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
