--- #YAML:1.0
name:               Test-WWW-Mechanize
version:            1.40
abstract:           Testing-specific WWW::Mechanize subclass
author:
    - Andy Lester <andy@petdance.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Assert::More:   0
    HTML::TreeBuilder:    0
    HTTP::Server::Simple:  0.42
    HTTP::Server::Simple::CGI:  0
    LWP:                  6.02
    perl:                 5.008
    Test::Builder::Tester:  1.09
    Test::LongString:     0.15
    Test::More:           0.96
    URI::file:            0
    WWW::Mechanize:       1.68
resources:
    bugtracker:  http://code.google.com/p/www-mechanize/issues/list
    homepage:    https://github.com/petdance/test-www-mechanize
    license:     http://www.opensource.org/licenses/artistic-license-2.0
    repository:  https://github.com/petdance/test-www-mechanize
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
